### ISSUE TITLE
字典新加完马上删除会报错

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#17]
17:45:56.661 ERROR   com.entdiy.errors[210] - ERR180203174556820: 系统运行错误，请联系管理员！ req.requestURI=/admin/sys/data-dict/delete, req.localPort=8080, req.xForwardedFor=null, req.header[user-agent]=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36, req.remoteUser=root[1], req.attr[org.springframework.web.servlet.DispatcherServlet.THEME_RESOLVER]=org.springframework.web.servlet.theme.FixedThemeResolver@15fd6689, session.attr[org.apache.shiro.subject.support.DefaultSubjectContext_AUTHENTICATED_SESSION_KEY]=true, req.method=POST, req.userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36, session.attr[org.apache.shiro.web.session.HttpServletSession.HOST_SESSION_KEY]=0:0:0:0:0:0:0:1, session.attr[org.apache.shiro.subject.support.DefaultSubjectContext_PRINCIPALS_SESSION_KEY]=root[1], req.attr[org.springframework.web.context.request.async.WebAsyncManager.WEB_ASYNC_MANAGER]=org.springframework.web.context.request.async.WebAsyncManager@42ce1795, req.header[referer]=http://localhost:8080/admin, req.serverPort=8080, req.header[origin]=http://localhost:8080, req.header[ajaxify]=true, req.localAddr=0:0:0:0:0:0:0:1, req.attr[org.springframework.web.servlet.DispatcherServlet.OUTPUT_FLASH_MAP]=FlashMap [attributes={}, targetRequestPath=null, targetRequestParams={}], req.requestURL=http://localhost:8080/admin/sys/data-dict/delete, req.attr[org.springframework.web.servlet.DispatcherServlet.THEME_SOURCE]=WebApplicationContext for namespace 'springServlet-servlet': startup date [Sat Feb 03 17:22:53 CST 2..., req.header[content-type]=application/x-www-form-urlencoded, req.serverName=localhost, req.clientId=0:0:0:0:0:0:0:1, req.header[host]=localhost:8080, req.attr[anyRoles.FILTERED]=true, req.remotePort=52664, req.user=root[1], req.attr[org.springframework.web.servlet.DispatcherServlet.FLASH_MAP_MANAGER]=org.springframework.web.servlet.support.SessionFlashMapManager@4a34f03, req.attr[org.springframework.session.SessionRepository.CURRENT_SESSION]=org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper$HttpSes..., req.attr[org.springframework.web.servlet.HandlerMapping.pathWithinHandlerMapping]=/admin/sys/data-dict/delete, req.attr[org.springframework.web.servlet.HandlerMapping.uriTemplateVariables]={}, req.attr[org.springframework.core.convert.ConversionService]=ConversionService converters =
	@org.springframework.format.annotation.DateTimeFormat java.lang.Long..., req.attr[authcAdmin.FILTERED]=true, req.header[accept-encoding]=gzip, deflate, br, req.remoteHost=0:0:0:0:0:0:0:1, req.param[ids]=jqg1, req.header[cookie]=Hm_lvt_5f64653382c3bd79af3c297bbafa5a6a=1517129885,1517644052; SESSION=NGE2NTA3NTgtNmNlZi00MzljLTljZGUtMmRiMDg1NDUxMDZm; sidebar_closed=0; Hm_lpvt_5f64653382c3bd79af3c297bbafa5a6a=1517649796, req.attr[org.sitemesh.webapp.contentfilter.BasicSelector.APPLIED_ONCE]=true, req.header[connection]=keep-alive, req.queryString=ids=jqg1, req.attr[org.springframework.web.servlet.HandlerMapping.bestMatchingPattern]=/admin/sys/data-dict/delete, req.attr[org.apache.shiro.spring.web.ShiroFilterFactoryBean$SpringShiroFilter.FILTERED]=true, req.header[x-requested-with]=XMLHttpRequest, req.attr[org.springframework.session.web.http.SessionRepositoryFilter.FILTERED]=true, req.attr[org.springframework.web.servlet.DispatcherServlet.LOCALE_RESOLVER]=org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver@c1320f, req.contextPath=, session.attr[shiroSavedRequest]=org.apache.shiro.web.util.SavedRequest@184918a2, req.header[accept-language]=zh-CN,zh;q=0.9,en;q=0.8, req.attr[org.springframework.session.SessionRepository]=org.springframework.session.data.redis.RedisOperationsSessionRepository@49b515de, req.attr[openEntityManagerInViewFilter.FILTERED]=true, req.header[content-length]=0, req.attr[encodingFilter.FILTERED]=true, req.attr[org.springframework.web.servlet.DispatcherServlet.CONTEXT]=WebApplicationContext for namespace 'springServlet-servlet': startup date [Sat Feb 03 17:22:53 CST 2..., req.localName=localhost, req.header[accept]=application/json, text/javascript, */*; q=0.01 
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long[]'; nested exception is java.lang.NumberFormatException: For input string: "jqg1"
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:131) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:124) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:161) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:131) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [servlet-api.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:na]

**Comment by hanyou** [comment]
马上修改也会报错，使用刷新按钮刷一下就不报错了。

**Comment by xautlx** [comment]
Fixed
