### ISSUE TITLE
字典用弹窗的方式新增保存不了

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#18]
17:48:17.613 ERROR   com.entdiy.errors[210] - ERR180203174817975: 系统运行错误，请联系管理员！ req.requestURI=/admin/sys/data-dict/edit, req.localPort=8080, req.xForwardedFor=null, req.param[secondaryValue]=, req.header[user-agent]=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36, req.remoteUser=root[1], req.param[disabled]=false, req.attr[org.springframework.web.servlet.DispatcherServlet.THEME_RESOLVER]=org.springframework.web.servlet.theme.FixedThemeResolver@15fd6689, session.attr[org.apache.shiro.subject.support.DefaultSubjectContext_AUTHENTICATED_SESSION_KEY]=true, req.method=POST, req.userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36, session.attr[org.apache.shiro.subject.support.DefaultSubjectContext_PRINCIPALS_SESSION_KEY]=root[1], session.attr[org.apache.shiro.web.session.HttpServletSession.HOST_SESSION_KEY]=0:0:0:0:0:0:0:1, req.attr[org.springframework.web.context.request.async.WebAsyncManager.WEB_ASYNC_MANAGER]=org.springframework.web.context.request.async.WebAsyncManager@5fa6a690, req.header[referer]=http://localhost:8080/admin, req.serverPort=8080, req.param[orderRank]=10, req.header[origin]=http://localhost:8080, req.localAddr=0:0:0:0:0:0:0:1, req.attr[org.springframework.web.servlet.DispatcherServlet.OUTPUT_FLASH_MAP]=FlashMap [attributes={}, targetRequestPath=null, targetRequestParams={}], req.requestURL=http://localhost:8080/admin/sys/data-dict/edit, req.attr[org.springframework.web.servlet.DispatcherServlet.THEME_SOURCE]=WebApplicationContext for namespace 'springServlet-servlet': startup date [Sat Feb 03 17:22:53 CST 2..., req.header[content-type]=application/x-www-form-urlencoded; charset=UTF-8, req.serverName=localhost, req.param[richTextValue]=, req.clientId=0:0:0:0:0:0:0:1, req.header[host]=localhost:8080, req.param[id]=, req.attr[anyRoles.FILTERED]=true, req.remotePort=52723, req.user=root[1], req.attr[org.springframework.web.servlet.DispatcherServlet.FLASH_MAP_MANAGER]=org.springframework.web.servlet.support.SessionFlashMapManager@4a34f03, req.attr[org.springframework.session.SessionRepository.CURRENT_SESSION]=org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper$HttpSes..., req.attr[org.springframework.web.servlet.HandlerMapping.pathWithinHandlerMapping]=/admin/sys/data-dict/edit, req.attr[org.springframework.web.servlet.HandlerMapping.uriTemplateVariables]={}, req.param[version]=0, req.attr[org.springframework.core.convert.ConversionService]=ConversionService converters =
	@org.springframework.format.annotation.DateTimeFormat java.lang.Long..., req.attr[authcAdmin.FILTERED]=true, req.param[parent.id]=undefined, req.header[accept-encoding]=gzip, deflate, br, req.remoteHost=0:0:0:0:0:0:0:1, req.header[cookie]=Hm_lvt_5f64653382c3bd79af3c297bbafa5a6a=1517129885,1517644052; SESSION=NGE2NTA3NTgtNmNlZi00MzljLTljZGUtMmRiMDg1NDUxMDZm; sidebar_closed=0; Hm_lpvt_5f64653382c3bd79af3c297bbafa5a6a=1517649796, req.attr[org.sitemesh.webapp.contentfilter.BasicSelector.APPLIED_ONCE]=true, req.header[connection]=keep-alive, req.queryString=null, req.attr[org.springframework.web.servlet.HandlerMapping.bestMatchingPattern]=/admin/sys/data-dict/edit, req.attr[org.apache.shiro.spring.web.ShiroFilterFactoryBean$SpringShiroFilter.FILTERED]=true, req.header[x-requested-with]=XMLHttpRequest, req.attr[org.springframework.session.web.http.SessionRepositoryFilter.FILTERED]=true, req.param[secondaryKey]=, req.param[imagePathValue]=, req.attr[org.springframework.web.servlet.DispatcherServlet.LOCALE_RESOLVER]=org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver@c1320f, req.param[primaryKey]=CONSULTANT_MODE, req.contextPath=, session.attr[shiroSavedRequest]=org.apache.shiro.web.util.SavedRequest@5c14fcd3, req.param[primaryValue]=咨询方式, req.header[accept-language]=zh-CN,zh;q=0.9,en;q=0.8, req.attr[org.springframework.session.SessionRepository]=org.springframework.session.data.redis.RedisOperationsSessionRepository@49b515de, req.attr[openEntityManagerInViewFilter.FILTERED]=true, req.header[content-length]=214, req.attr[encodingFilter.FILTERED]=true, req.attr[org.springframework.web.servlet.DispatcherServlet.CONTEXT]=WebApplicationContext for namespace 'springServlet-servlet': startup date [Sat Feb 03 17:22:53 CST 2..., req.localName=localhost, req.param[filePathValue]=, req.header[accept]=application/json, text/javascript, */*; q=0.01 
org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'entity' on field 'parent.id': rejected value [undefined]; codes [typeMismatch.entity.parent.id,typeMismatch.parent.id,typeMismatch.id,typeMismatch.java.lang.Long,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [entity.parent.id,parent.id]; arguments []; default message [parent.id]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Long' for property 'parent.id'; nested exception is java.lang.NumberFormatException: For input string: "undefined"]
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:157) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:124) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:161) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:131) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [servlet-api.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855) [spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.27]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.27]
	at org.sitemesh.webapp.contentfilter.ContentBufferingFilter.bufferAndPostProcess(ContentBufferingFilter.java:169) [sitemesh-3.0.0.jar:na]
	at org.sitemesh.webapp.contentfilter.ContentBufferingFilter.doFilter(ContentBufferingFilter.java:126) [sitemesh-3.0.0.jar:na]
	at org.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:120) [sitemesh-3.0.0.jar:na]

**Comment by xautlx** [comment]
Fixed
