### ISSUE TITLE
在新表中添加OneToOne Account启动报错

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#19]
@MetaData(value = "帐号")
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "account_id", nullable = false)
    private Account account;

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilter' defined in file [/Users/hanyou/ZhijianProjects/apache-tomcat-8.5.27/webapps/ROOT/WEB-INF/classes/service/spring-shiro.xml]: Cannot resolve reference to bean 'siteFormAuthenticationFilter' while setting bean property 'filters' with key [TypedStringValue: value [authcSite], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteFormAuthenticationFilter' defined in file [/Users/hanyou/ZhijianProjects/apache-tomcat-8.5.27/webapps/ROOT/WEB-INF/classes/service/spring-shiro.xml]: Cannot resolve reference to bean 'accountService' while setting bean property 'accountService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountService': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in file [/Users/hanyou/ZhijianProjects/apache-tomcat-8.5.27/webapps/ROOT/WEB-INF/classes/context/spring-jpa.xml]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: No identifier specified for entity: xyz.entdiy.party.entity.Customer
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:426) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:167) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]

**Comment by hanyou** [comment]
是没有加extends BaseNativeEntity，已解决
