### ISSUE TITLE
很多菜单打开报错 请求异常 E400： 数据请求异常，请联系管理员

### ISSUE THREAD

**Issue by andyadc** [xautlx/s2jh4net#28]
很多菜单打开报错 请求异常 E400： 数据请求异常，请联系管理员
如公告管理, 菜单管理

异常日志:
10-May-2018 15:57:43.349 信息 [http-nio-8080-exec-4] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP
 request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in
RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:479)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by xautlx** [comment]
tomcat版本过高，降低tomcat即可。或者：

修改catalina.properties 中的配置项中开启下边这个配置即可：

tomcat.util.http.parser.HttpParser.requestTargetAllow=|
